-- DDL
-- CREATE
-- ALTER
-- DROP




USE Ecommerce
CREATE TABLE Usuarios(
Id INT PRIMARY KEY NOT NULL,
Nome VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
Senha VARCHAR(50) NOT NULL,
Endereco VARCHAR(100) NOT NULL,
)

CREATE TABLE Produtos(
Id INT PRIMARY KEY IDENTITY NOT NULL,
NomeProduto VARCHAR(50) NOT NULL,
Descricao VARCHAR(200) NOT NULL,
Preco FLOAT NOT NULL,
Foto VARCHAR(200) NOT NULL,
Estoque INT NOT NULL,
FK_Criador INT NOT NULL,
FOREIGN KEY (FK_Criador) REFERENCES Usuarios (Id)
)

CREATE TABLE Compra(
Quantidade INT NOT NULL,
FK_Comprador INT NOT NULL,
FK_Produto INT NOT NULL,
FOREIGN KEY (FK_Comprador) REFERENCES Usuarios(Id),
FOREIGN KEY (FK_Produto) REFERENCES Produtos(Id)
)

