-- DDL
-- CREATE
-- ALTER
-- DROP


USE [Rede Social]
CREATE TABLE Usuarios(
Id INT PRIMARY KEY NOT NULL,
Email VARCHAR(50) NOT NULL,
Senha VARCHAR(50) NOT NULL,
)

CREATE TABLE PerfilPessoal(
Id INT PRIMARY KEY NOT NULL,
Nome VARCHAR(50) NOT NULL,
Endereco VARCHAR(100) NOT NULL,
DataNasc INT NOT NULL,
Genero VARCHAR(20) NOT NULL,
Seguidores INT NOT NULL,
Seguindo INT NOT NULL,
FK_Usuario INT NOT NULL,
FOREIGN KEY (FK_Usuario) REFERENCES Usuarios (Id)
)

CREATE TABLE Postagem(
Id INT PRIMARY KEY NOT NULL,
Texto VARCHAR(200) NULL,
Autor VARCHAR(50) NOT NULL,
Imagem VARCHAR(150) NULL,
FK_CriadorConteudo INT NOT NULL,
FOREIGN KEY (FK_CriadorConteudo) REFERENCES PerfilPessoal (Id)
)

CREATE TABLE Interacao(
Id INT PRIMARY KEY NOT NULL,
Curtida INT NULL,
Comentário VARCHAR(100) NULL,
FK_Autor INT NOT NULL,
FOREIGN KEY (FK_Autor) REFERENCES PerfilPessoal (Id),
FK_Likes INT NOT NULL,
FOREIGN KEY (FK_Likes) REFERENCES Postagem (Id)
)

CREATE TABLE Chat(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Conversa VARCHAR(150) NOT NULL,
DataUltimaConversa VARCHAR(50) NOT NULL,
HoraUltimaConversa VARCHAR(50) NOT NULL,
FK_ConversaFrom INT NOT NULL,
FOREIGN KEY (FK_ConversaFrom) REFERENCES PerfilPessoal (Id),
FK_ConversaTo INT NOT NULL,
FOREIGN KEY (FK_ConversaTo) REFERENCES PerfilPessoal (Id)
)
