-- DDL
-- CREATE
-- ALTER
-- DROP




USE MarketPlace
CREATE TABLE Usuarios(
Id INT PRIMARY KEY NOT NULL,
Nome VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
Senha VARCHAR(50) NOT NULL,
Endereco VARCHAR(100) NOT NULL,
)

CREATE TABLE Produtos(
Id INT PRIMARY KEY IDENTITY NOT NULL,
NomeProduto VARCHAR(50) NOT NULL,
Descricao VARCHAR(200) NOT NULL,
Preco FLOAT NOT NULL,
Foto VARCHAR(200) NOT NULL,
Estoque INT NOT NULL,
FK_Anunciante INT NOT NULL,
FOREIGN KEY (FK_Anunciante) REFERENCES Usuarios (Id)
)

CREATE TABLE Venda(
Estoque INT NOT NULL,
FK_Vendedor INT NOT NULL,
FK_Produto INT NOT NULL,
FOREIGN KEY (FK_Vendedor) REFERENCES Usuarios(Id),
FOREIGN KEY (FK_Produto) REFERENCES Produtos(Id)
)

CREATE TABLE Compra(
Quantidade INT NOT NULL,
FK_Comprador INT NOT NULL,
FK_Produto INT NOT NULL,
FOREIGN KEY (FK_Comprador) REFERENCES Usuarios(Id),
FOREIGN KEY (FK_Produto) REFERENCES Produtos(Id)
)



